In [1]:
import pandas as pd
sales_data = {
    "Transaction ID": [101, 102, 103, 104],
    "Customer ID": [1, 2, 3, 2],
    "Amount": [250.50, 150.00, 300.75, 200.00],
    "Date": ["2025-01-10", "2025-01-11", "2025-01-12", "2025-01-13"]
}

customer_data = {
    "Customer ID": [1, 2, 3, 4],
    "Customer Name": ["Alice", "Bob", "Charlie", "Diana"],
    "Age": [30, 25, 35, 40],
    "City": ["New York", "Los Angeles", "Chicago", "Houston"]
}

sales_df = pd.DataFrame(sales_data)
customer_df = pd.DataFrame(customer_data)


sales_df

Transaction ID  Customer ID  Amount        Date
0             101            1  250.50  2025-01-10
1             102            2  150.00  2025-01-11
2             103            3  300.75  2025-01-12
3             104            2  200.00  2025-01-13

In [7]:
customer_df

Customer ID Customer Name  Age         City
0            1         Alice   30     New York
1            2           Bob   25  Los Angeles
2            3       Charlie   35      Chicago
3            4         Diana   40      Houston

In [9]:
sales_df.describe()

Transaction ID  Customer ID      Amount
count        4.000000     4.000000    4.000000
mean       102.500000     2.000000  225.312500
std          1.290994     0.816497   64.904858
min        101.000000     1.000000  150.000000
25%        101.750000     1.750000  187.500000
50%        102.500000     2.000000  225.250000
75%        103.250000     2.250000  263.062500
max        104.000000     3.000000  300.750000

In [11]:
sales_df.shape

(4, 4)

In [29]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[12,54,23,13,87]])
print(arr)
print('0th element on 1nd row: ', arr[0,3])
print('5th element on 2nd row: ', arr[1,4])
print('3th element on 3nd row: ', arr[2,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [12 54 23 13 87]]
0th element on 1nd row:  4
5th element on 2nd row:  10
3th element on 3nd row:  23


In [41]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],])
print(arr)
print(arr[1,1,2])
# print(arr[0,2,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


In [45]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]
